name: essenziale_storage
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  image: ^4.5.4
  mime: ^2.0.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
