name: essenziale_storage
description: A sample command-line application.
version: 1.0.0
to_publish: none

environment:
  sdk: ^3.9.3

dependencies:
  collection: ^1.19.1
  image: ^4.5.4
  mime: ^2.0.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  gcloud: ^0.9.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  shelf_dynamic_forwarder: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
